export const USER_SET_INFO = 'USER_SET_INFO'
export const USER_SET_USERNAME = 'USER_SET_USERNAME'

export const STUDENT_GET_INFO = 'STUDENT_GET_INFO'
export const STUDENT_REFRESH_INFO = 'STUDENT_REFRESH_INFO'
export const STUDENT_FETCH_ERROR = 'STUDENT_FETCH_ERROR'
