export const USER_GET_INFO = 'USER_GET_INFO'
export const STUDENT_GET_INFO = 'STUDENT_GET_INFO'
export const STUDENT_GET_FEE = 'STUDENT_GET_FEE'
export const STUDENT_REFRESH_INFO = 'STUDENT_REFRESH_INFO   '
